Sample Configurations for 4.0 version

----TM----
[server]
hostname = "localhost"
node_ip = "127.0.0.1"
server_role = "traffic-manager"
offset=2

[user_store]
type = "database_unique_id"

[super_admin]
username = "admin"
password = "admin"
create_admin_account = true

[database.shared_db]
type = "mysql"
hostname = "db.wso2.com"
name = "shared_db"
port = "3306"
username = "root"
password = "root"

[keystore.tls]
file_name =  "wso2carbon.jks"
type =  "JKS"
password =  "wso2carbon"
alias =  "wso2carbon"
key_password =  "wso2carbon"

[truststore]
file_name = "client-truststore.jks"
type = "JKS"
password = "wso2carbon"

[apim.event_hub]
enable = true
username = "$ref{super_admin.username}"
password = "$ref{super_admin.password}"
service_url = "https://localhost:9443/services/"
event_listening_endpoints = ["tcp://localhost:5672", "tcp://localhost:5673"]

----If TM is HA----

[apim.throttling]
event_duplicate_url = ["tcp://localhost:5675"]
throttle_decision_endpoints = ["tcp://localhost:5674"]

----CP----

[server]
hostname = "localhost"
node_ip = "127.0.0.1"
offset=0

[user_store]
type = "database_unique_id"

[super_admin]
username = "admin"
password = "admin"
create_admin_account = true

[database.apim_db]
type = "mysql"
hostname = "db.wso2.com"
name = "apim_db"
port = "3306"
username = "root"
password = "root"

[database.shared_db]
type = "mysql"
hostname = "db.wso2.com"
name = "shared_db"
port = "3306"
username = "root"
password = "root"

[keystore.tls]
file_name =  "wso2carbon.jks"
type =  "JKS"
password =  "wso2carbon"
alias =  "wso2carbon"
key_password =  "wso2carbon"

[truststore]
file_name = "client-truststore.jks"
type = "JKS"
password = "wso2carbon"

[[apim.gateway.environment]]
name= "Production and Sandbox"
type= "hybrid"
display_in_api_console= true
show_as_token_endpoint_url = true
description= "This is a hybrid gateway that handles both production and sandbox token traffic."
service_url= "https://localhost:9447/services/"
http_endpoint = "http://localhost:8284"
https_endpoint = "https://localhost:8247"
username= "${admin.username}"
password= "${admin.password}"

----If CP is HA----

# Event Hub configurations
[apim.event_hub]
enable = true
username = "$ref{super_admin.username}"
password = "$ref{super_admin.password}"
service_url = "https://localhost:9443/services/"
event_listening_endpoints = ["tcp://localhost:5672"]
event_duplicate_url = ["tcp://localhost:5673"]

[[apim.event_hub.publish.url_group]]
urls = ["tcp://localhost:9611"]
auth_urls = ["ssl://localhost:9711"]

[[apim.event_hub.publish.url_group]]
urls = ["tcp://localhost:9612"]
auth_urls = ["ssl://localhost:9712"]


----If there is a TM and HA----

[apim.throttling]
service_url = "https://localhost:9445/services/"
throttle_decision_endpoints = ["tcp://localhost:5674","tcp://localhost:5675"]

[[apim.throttling.url_group]]
traffic_manager_urls = ["tcp://localhost:9613"]
traffic_manager_auth_urls = ["ssl://localhost:9713"]

[[apim.throttling.url_group]]
traffic_manager_urls = ["tcp://localhost:9614"]
traffic_manager_auth_urls = ["ssl://localhost:9714"]

----If there is a TM----

[apim.throttling]
service_url = "https://localhost:9445/services/"
throttle_decision_endpoints = ["tcp://localhost:5674"]

[[apim.throttling.url_group]]
traffic_manager_urls = ["tcp://localhost:9613"]
traffic_manager_auth_urls = ["ssl://localhost:9713"]

------

[apim.devportal]
url = "https://localhost:9443/devportal"

[apim.key_manager]
service_url = "https://localhost:9443/services/"

[[event_listener]]
id = "token_revocation"
type = "org.wso2.carbon.identity.core.handler.AbstractIdentityHandler"
name = "org.wso2.is.notification.ApimOauthEventInterceptor"
order = 1

[event_listener.properties]
notification_endpoint = "https://localhost:9443/internal/data/v1/notify"
username = "${admin.username}"
password = "${admin.password}"
'header.X-WSO2-KEY-MANAGER' = "default"


----GW----

[server]
hostname = "localhost"
node_ip = "127.0.0.1"
server_role = "gateway-worker"
offset=4

[user_store]
type = "database_unique_id"

[super_admin]
username = "admin"
password = "admin"
create_admin_account = true

[database.shared_db]
type = "mysql"
hostname = "db.wso2.com"
name = "shared_db"
port = "3306"
username = "root"
password = "root"

[keystore.tls]
file_name =  "wso2carbon.jks"
type =  "JKS"
password =  "wso2carbon"
alias =  "wso2carbon"
key_password =  "wso2carbon"

[truststore]
file_name = "client-truststore.jks"
type = "JKS"
password = "wso2carbon"

[apim.sync_runtime_artifacts.gateway]
gateway_labels =["Default"]

[apim.key_manager]
service_url = "https://localhost:9443/services/"

----If TM is HA----

[apim.throttling]
throttle_decision_endpoints = ["tcp://localhost:5674","tcp://localhost:5675"]

[[apim.throttling.url_group]]
traffic_manager_urls = ["tcp://localhost:9613"]
traffic_manager_auth_urls = ["ssl://localhost:9713"]

[[apim.throttling.url_group]]
traffic_manager_urls = ["tcp://localhost:9614"]
traffic_manager_auth_urls = ["ssl://localhost:9714"]

----If there is a TM----

[apim.throttling]
throttle_decision_endpoints = ["tcp://localhost:5674"]

[[apim.throttling.url_group]]
traffic_manager_urls = ["tcp://localhost:9613"]
traffic_manager_auth_urls = ["ssl://localhost:9713"]

----If there is no TM but one CP----

[apim.throttling]
service_url = "https://localhost:9443/services/"
throttle_decision_endpoints = ["tcp://localhost:5672"]

[[apim.throttling.url_group]]
traffic_manager_urls = ["tcp://localhost:9611"]
traffic_manager_auth_urls = ["ssl://localhost:9711"]

----If there is no TM but HA CP----

[apim.throttling]
service_url = "https://localhost:9445/services/"
throttle_decision_endpoints = ["tcp://localhost:5672","tcp://localhost:5673"]

[[apim.throttling.url_group]]
traffic_manager_urls = ["tcp://localhost:9612"]
traffic_manager_auth_urls = ["ssl://localhost:9712"]

[[apim.throttling.url_group]]
traffic_manager_urls = ["tcp://localhost:9613"]
traffic_manager_auth_urls = ["ssl://localhost:9713"]

----If there is a TM and CP HA----

[apim.event_hub]
enable = true
username = "$ref{super_admin.username}"
password = "$ref{super_admin.password}"
service_url = "https://localhost:9443/services/"
event_listening_endpoints = ["tcp://localhost:5672", "tcp://localhost:5673"]

----If there is a TM and one CP----

[apim.event_hub]
enable = true
username = "$ref{super_admin.username}"
password = "$ref{super_admin.password}"
service_url = "https://localhost:9443/services/"
event_listening_endpoints = ["tcp://localhost:5672"]

-----

[apim.cors]
allow_origins = "*"
allow_methods = ["GET","PUT","POST","DELETE","PATCH","OPTIONS"]
allow_headers = ["authorization","Access-Control-Allow-Origin","Content-Type","SOAPAction"]
allow_credentials = false