[server]
hostname = "localhost"
node_ip = "127.0.0.1"
server_role = "traffic-manager"
offset = 2

[user_store]
type = "database_unique_id"

[super_admin]
username = "admin"
password = "admin"
create_admin_account = true

[database.shared_db]
type = "mysql"
hostname = "${db_host}"
name = "${shared_db_name}"
port = "${db_port}"
username = "${db_user}"
password = "${db_password}"

[keystore.tls]
file_name = "wso2carbon.jks"
type = "JKS"
password = "wso2carbon"
alias = "wso2carbon"
key_password = "wso2carbon"

[truststore]
file_name = "client-truststore.jks"
type = "JKS"
password = "wso2carbon"

[apim.event_hub]
enable = true
username = "$ref{super_admin.username}"
password = "$ref{super_admin.password}"
service_url = "https://localhost:9443/services/"
event_listening_endpoints = ["tcp://localhost:5672", "tcp://localhost:5673"]